name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Change directory
        run: cd hahu_cypress
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Run Cypress tests
        run: npm run cypress-test-run-windows
